apiVersion: v1
kind: Namespace
metadata:
  name: operator
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workshopoperators.mgmworkshop.com

spec:
  group: mgmworkshop.com
  version: v1
  names:
    kind: WorkshopOperator
    plural: workshopoperators
    singular: workshopoperator
  scope: Namespaced
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: workshop-operator-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - mgmworkshop.com
    resources:
      - workshopoperators
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: workshop-operator-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workshop-operator-clusterrole
subjects:
  - kind: ServiceAccount
    name: workshop-operator
    namespace: operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: operator
  name: workshop-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-operator
  namespace: operator
  labels: &labels
    app: workshop-operator
spec:
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: workshop-operator
      containers:
        - image: lamth2/workshop-operator
          name: workshop-operator
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
