apiVersion: v1
kind: Namespace
metadata:
  name: operator
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workshopoperators.mgmworkshop.com
spec:
  group: mgmworkshop.com
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: WorkshopOperator
    plural: workshopoperators
    singular: workshopoperator
  scope: Namespaced
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: workshop-operator-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - traefik.containo.us
    resources:
      - middlewares
      - ingressroutes
      - traefikservices
      - ingressroutetcps
      - ingressrouteudps
      - tlsoptions
      - tlsstores
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - mgmworkshop.com
    resources:
      - workshopoperators
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: workshop-operator-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workshop-operator-clusterrole
subjects:
  - kind: ServiceAccount
    name: workshop-operator
    namespace: operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: operator
  name: workshop-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-operator
  namespace: operator
  labels: &labels
    app: workshop-operator
spec:
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: workshop-operator
      containers:
        - image: lamth2/workshop-operator
          name: workshop-operator
          ports:
            - containerPort: 8080
---
